Drastic Rewrite
skraynick/MycroftCore-Android pull request #2
Opened 2019-03-18 22:18 UTC by Tadashi-Hikari

This is a drastic rewrite of the whole project. It merges all the separate modules into the main module, with the intention of simplifying the install for users. It launches but does not work yet

2019-03-19 14:47 UTC, skraynick requested changes
See comments.

2019-03-19 14:47 UTC, skraynick commented on Mycroft-Core/src/main/AndroidManifest.xml
> +            android:name=".coredatabases.MycroftContentProvider"
Stick to camelCase.

2019-03-19 14:47 UTC, skraynick commented on Mycroft-Core/src/main/java/www/mabase/tech/mycroft/MycroftService.java
> +       /* // Create and send a message to the service, using a supported 'what' value
// or /* for multiline. Just a FYI.

2019-03-19 14:47 UTC, skraynick commented on Mycroft-Core/src/main/java/www/mabase/tech/mycroft/mycroftstt/PocketSphinxService.java
> +        Intent bindToMycroftService = new Intent();
Services are often started on their own threads,, so that would be a good practice in this case.

2019-03-19 14:47 UTC, skraynick commented on .idea/dictionaries/chris.xml
> +<component name="ProjectDictionaryState">
the .idea files are usually git ignore, unless you have a reason for them..

2019-03-19 14:47 UTC, skraynick commented on Mycroft-Core/src/main/AndroidManifest.xml
> +            android:name=".coredatabases.MycroftContentProvider"
What naming case... stick to camelCase.

2019-03-22 03:14 UTC, Tadashi-Hikari commented on Mycroft-Core/src/main/java/www/mabase/tech/mycroft/mycroftstt/PocketSphinxService.java
> +        Intent bindToMycroftService = new Intent();
This is binding to an already started service. The bulk of PocketSphinxService is already split off into its own Async thread in the service itself. Maybe I need to re-evaluate the structure?

2019-03-22 03:34 UTC, Tadashi-Hikari commented
I've made some of the the changes. I'm going to close this and make a new pull request

2019-03-22 03:37 UTC, closed without merging